"""empty message

Revision ID: 0e4bc5938bc7
Revises: 76cdef0dc6a6
Create Date: 2024-11-09 13:44:27.618535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0e4bc5938bc7'
down_revision: Union[str, None] = '76cdef0dc6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    # ### end Alembic commands ###
