"""empty message

Revision ID: 4e8c83cd3374
Revises: b06474b11f56
Create Date: 2024-11-20 10:00:19.041263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4e8c83cd3374'
down_revision: Union[str, None] = 'b06474b11f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text("'2024-11-20 10:00:14.334532'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
