"""empty message

Revision ID: 63291ffe8000
Revises: 28a9d264a9d9
Create Date: 2024-10-26 17:01:05.840923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '63291ffe8000'
down_revision: Union[str, None] = '28a9d264a9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_trabajador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('correo_trabajador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('telefono_trabajador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('localidad_trabajador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('correo')
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('correo_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('localidad_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('correo')
        batch_op.drop_column('localidad')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('localidad_usuario')
        batch_op.drop_column('correo_usuario')
        batch_op.drop_column('nombre_usuario')

    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('localidad_trabajador')
        batch_op.drop_column('telefono_trabajador')
        batch_op.drop_column('correo_trabajador')
        batch_op.drop_column('nombre_trabajador')

    # ### end Alembic commands ###
