"""empty message

Revision ID: 76cdef0dc6a6
Revises: 4799c5702c76
Create Date: 2024-11-04 20:24:14.696769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '76cdef0dc6a6'
down_revision: Union[str, None] = '4799c5702c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['trabajador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('correo_trabajador')
        batch_op.drop_column('password_trabajador')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('correo_usuario')
        batch_op.drop_column('password_usuario')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_usuario', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('correo_usuario', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_trabajador', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('correo_trabajador', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=False))

    op.drop_table('login')
    # ### end Alembic commands ###
