"""empty message

Revision ID: 85ccf2f0f077
Revises: aad13a82330a
Create Date: 2024-10-27 21:53:00.662530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '85ccf2f0f077'
down_revision: Union[str, None] = 'aad13a82330a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.alter_column('nombre_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('correo_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('telefono_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('localidad_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('localidad_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('telefono_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('correo_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('nombre_trabajador',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
