"""empty message

Revision ID: 918d4bf53dc1
Revises: e944c50b74b5
Create Date: 2024-11-18 10:14:42.157325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '918d4bf53dc1'
down_revision: Union[str, None] = 'e944c50b74b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('direccion_usuario')

    # ### end Alembic commands ###
